@startuml
hide footbox

participant ":iGraduate" as iGraduate
participant ":Parser" as Parser
participant ":AddCommand" as AddCommand
participant ":Module" as Module
participant ":ModuleList" as ModuleList
participant ":Storage" as Storage
participant ":Ui" as Ui

iGraduate -> Parser: parseCommand("add Programming -c CS1010 -mc 4 -t core")
activate Parser #FFBBBB

Parser -> Parser: createAddCommand(commandParameters, commandFlags)
activate Parser #DarkSalmon

create AddCommand
Parser -> AddCommand: AddCommand("CS1010", ["-c", "CS1010", "-mc", 4, "-t", "core"])
activate AddCommand
AddCommand --> Parser: new AddCommand("CS1010", ["-c", "CS1010", "-mc", 4, "-t", "core"])
deactivate AddCommand
deactivate Parser

Parser -> iGraduate: new AddCommand("CS1010", ["-c", "CS1010", "-mc", 4, "-t", "core"])
deactivate Parser

iGraduate -> AddCommand: execute(moduleList, ui, storage)
activate AddCommand

AddCommand -> AddCommand: createModuleByType()
activate AddCommand #DarkSalmon
AddCommand -> Module: new Module("CS1010", "Programming Methodology", 4.0, "not taken", "nil", ArrayList<String> preRequisites, ArrayList<String> untakenPreRequisites)
activate Module
return module:Module
return module:Module

AddCommand -> ModuleList: add(module:Module)
activate ModuleList
deactivate ModuleList

AddCommand -> Storage: saveModulesToFile(moduleList:ModuleList)
activate Storage
deactivate Storage

AddCommand -> Ui: printAddedModuleSuccess(module:Module)
activate Ui
deactivate Ui

deactivate AddCommand
destroy AddCommand
@enduml