@startuml
hide footbox

Participant ":iGraduate" as iGraduate
Participant ":Ui" as ui
Participant ":Parser" as parser
Participant ":Command" as command

activate iGraduate

iGraduate -> iGraduate: run()
activate iGraduate #DarkSalmon

iGraduate -> ui:printWelcomeMessage()
activate ui
return

loop while !isExit
    iGraduate -> ui: getCommand()
    activate ui
    return fullCommand:String

    iGraduate -> ui: printBorderLine()
    activate ui
    return

    iGraduate -> parser: parseCommand(fullCommand:String)
    activate parser
    parser -> parser: createCommand()
    activate parser #DarkSalmon

    create command
    parser -> command: createCommand()
    activate command
    return c:Command
    return
    return c:Command

    iGraduate -> command: execute(c:Command)
    activate command
    return

    iGraduate -> command: isExit(c:Command)
    activate command
    return isExit:Boolean

    iGraduate -> ui: printBorderLine()
    activate ui
    return
    destroy command
end
return

iGraduate --[hidden]> iGraduate
destroy iGraduate
destroy ui
destroy parser
@enduml