@startuml
hide circle
skinparam classAttributeIconSize 0

Parser"1" <-- iGraduate
Parser : +parseCommand(String line):Command

Parser : +createCommand(String[] commandParameters, String[] commandFlags):Command

iGraduate : +run()
iGraduate : +main()
@enduml