@startuml
hide footbox

participant ":iGraduate" as iGraduate
participant ":Parser" as Parser
participant ":DoneCommand" as DoneCommand

iGraduate -> Parser: parseCommand("done CS1010 -g A")
activate Parser

Parser -> Parser: getCommand(line:String)
activate Parser #DarkSalmon
return command:String

Parser -> Parser: getCommandParametersAndFlags(commands:ArrayList<String>)
activate Parser #DarkSalmon
return commandParameterAndFlags:ArrayList<String>

Parser -> Parser: createDoneCommand(commandParameters:ArrayList<String>, commandFlags:ArrayList<String>)
activate Parser #DarkSalmon

create DoneCommand
Parser -> DoneCommand: DoneCommand("CS1010", "A")
activate DoneCommand
DoneCommand --> Parser: new DoneCommand("CS1010", "A")
deactivate DoneCommand
deactivate Parser
Parser --> iGraduate: new DoneCommand("CS1010", "A")

deactivate Parser

@enduml