@startuml
hide footbox

participant ":iGraduate" as iGraduate
participant ":Parser" as Parser
participant ":DoneCommand" as DoneCommand

iGraduate -> Parser: parseCommand("done CS1010 -g A")
activate Parser

Parser -> Parser: getCommand(line:String)
activate Parser #DarkSalmon
return command:String

Parser -> Parser: getCommandParametersAndFlags(commands:String[])
activate Parser #DarkSalmon
return commandParameterAndFlags:String[]

Parser -> Parser: createDoneCommand(commandParameters:String[], commandFlags:String[])
activate Parser #DarkSalmon

create DoneCommand
Parser -> DoneCommand: new
activate DoneCommand
DoneCommand --> Parser: new DoneCommand("CS1010", "A")
deactivate DoneCommand
deactivate Parser
Parser --> iGraduate: new DoneCommand("CS1010", "A")

deactivate Parser

@enduml